"""first commit

Revision ID: 32acc427290a
Revises: 
Create Date: 2023-02-08 01:31:17.320033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32acc427290a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('alarm', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persons')
    # ### end Alembic commands ###
